Halo/Halo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('disk/', include('disk.urls')),
    path('music/', include('music.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Halo/disk/urls.py
from django.urls import path, re_path

from .views import index
from .views import about
from .views import other_page
from .views import change_name, \
                   upload_files, \
                   create_file,\
                   delete_file,\
                   delete_folder,\
                   create_folder,\
                   download_file, \
                   download_folder

from .views import RegisterUserView, RegisterDoneView
from .views import DiskLoginView, DiskLogoutView
from .views import DeleteUserView
from .views import DiskPasswordChangeView
from .views import ChangeUserInfoView

# Добавляем пространство имен
# Это поможет при рендеринге, можно указывать
# <namespace>:<app_name> <=> disk:upload
app_name = 'disk'

urlpatterns = [
    #    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),

    path('accounts/password/change/', DiskPasswordChangeView.as_view(), name='password_change'),

    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),

    # Путь к странцие входа
    path('accounts/login/', DiskLoginView.as_view(), name='login'),
    path('accounts/logout/', DiskLogoutView.as_view(), name='logout'),

    # sha_256(function_name) -> token
    # example: sha_256('about') -> a4262e1c9bcbc1721eb3fe13558154460a2b2a2d307daa32532478526ce6ccb1
    re_path(r'^63b8d67eb1ca393b5e69b31a5d126d553a3fb94afd7a60c90049e66c66c6b891/(?P<path>.*)', change_name, name='change_name'),
    re_path(r'^463d52e2aaa10e704eb0b24dea0eea8e9b86e38d52c28993eeebcf6ec01ec347/(?P<path>.*)', create_file, name='create_file'),
    re_path(r'^87b5c6b2b1e3e19601b421b8b81e199e4d27876d045610b5dcf078017caee694/(?P<path>.*)', delete_file, name='delete_file'),
    re_path(r'^5b53fba3b9601c8aa7ff13ce2d164f427a54f49b8873fa382e310f2162e0db08/(?P<path>.*)', create_folder, name='create_folder'),
    re_path(r'^e2a7114fca4f6f72dbfedc267c06cd4ff38644dbf11bae90efdf4d19c7ee7474/(?P<path>.*)', delete_folder, name='delete_folder'),
    re_path(r'^a3b2ceb1f2d110bf6c5f9f261a6f448a5be06e2e1a515e3e65bf7943300f89a3/(?P<path>.*)', upload_files, name='upload_files'),

    re_path(r'^b8c75dbaff47e7a2a24fb979a5c9f4bb91a22f8a83456c6006a6d21613c33f64/(?P<path>.*)', download_folder, name='download_folder'),
    re_path(r'^7898193c2ce6c4b3117e9ed4a3f09e615dd0cd89c3370770983e678b0c00e558/(?P<path>.*)', download_file, name='download_file'),
    path('a4262e1c9bcbc1721eb3fe13558154460a2b2a2d307daa32532478526ce6ccb1/', about, name='about'),
    re_path(r'^(?P<folder>.*)', other_page, name='other'),
    path('', index, name='index'),
]

Halo/music/urls.py
from django.urls import path

from .views import index, media_create
app_name = 'music'

urlpatterns = [
    path('add/', media_create, name='media_create'),
    path('', index, name='index'),
]

Halo/disk/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import AbstractUser


class DiskUser(AbstractUser):

    class Meta(AbstractUser.Meta):
        pass

Halo/disk/forms.py
from django import forms

# Форма регистрации
from .models import DiskUser
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError


# Регистрацция
class RegisterUserForm(forms.ModelForm):
    # Полное объявление - обязательно для заполнения:
    email = forms.EmailField(required=True,
                             label='Адрес электронной почты')
    password1 = forms.CharField(label='Пароль',
                                widget=forms.PasswordInput,
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Пароль (повторно)',
                                widget=forms.PasswordInput,
                                help_text='Введите тот же самый пароль еще раз для проверки')

    # Валидация пароля
    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    # Проверка совпадения введеннных паролей
    def clean(self):
        super().clean()
        # cleaned_data = super(RegisterUserForm, self).clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError(
                'Введенные пароли не совпадают',
                code='password_mismatch'
            )
            }
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

    class Meta:
        model = DiskUser
        fields = ('username', 'email', 'password1', 'password2',
                  'first_name', 'last_name')


class ChangeUserInfoForm(forms.ModelForm):
    # Выполняем полное объявление поля email модели DiskUser
    # Так как оно обязательно
    email = forms.EmailField(required=True,
                             label='Адрес электронной почты')
    class Meta:
        model = DiskUser
        fields = ('username', 'email', 'first_name', 'last_name')

Halo/disk/views.py
from django.shortcuts import render
from django.template import loader

# Получить содержимое диска
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import TemplateDoesNotExist

# Загрузка файлов в определенный каталог
from django.core.files.storage import FileSystemStorage

# Регистрация
from .models import DiskUser
from .forms import RegisterUserForm
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views.generic.base import TemplateView

# Удаление пользователя:
from django.views.generic.edit import DeleteView
from django.contrib.auth import logout
from django.shortcuts import get_object_or_404

# Для старницы входа
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required

# Для старницы выхода (дполнительно)
# Чтобы страица была доступна только зарегистрированным пользователям
from django.contrib.auth.views import LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin

# Изменение пароя
from django.contrib.auth.views import PasswordChangeView

# Изменение личной информации
from django.views.generic.edit import UpdateView
from .forms import ChangeUserInfoForm

# Дополниельные приложения
from .utilities import rename
from .utilities import folder_archive
from .utilities import get_link_create
from .utilities import get_link_delete
from .utilities import create_user_file
from .utilities import delete_user_file
from .utilities import create_user_folder
from .utilities import delete_user_folder
from .utilities import get_user_folder_content


@login_required
def index(request):
    template = loader.get_template('disk/index.html')
    # Получаем каталог пользователя по его ID
    user_id = str(request.user.id)
    objects = get_user_folder_content(user_id)

    context = {
        'path': "",
        'folders': objects[0],
        'files': objects[1],
    }
    return HttpResponse(template.render(context, request))


def about(request):
    template = loader.get_template('disk/about.html')
    return HttpResponse(template.render({}, request))


@login_required
def other_page(request, folder):
    try:
        template = loader.get_template('disk/index.html')

        # Получаем каталог пользователя по его ID
        user_id = str(request.user.id)
        objects = get_user_folder_content(user_id + '/' + folder)

        context = {
            'path': folder,
            'folders': objects[0],
            'files': objects[1],
        }
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(context, request))


@login_required
def upload_files(request, path):
    redirect = get_link_create(path)
    user_id = str(request.user.id)
    folder = 'media/' + user_id + '/' + path

    # Устанавливаем путь для сохранения
    fs = FileSystemStorage(location=folder)
    fs.save(request.FILES['file'].name, request.FILES['file'])

    return HttpResponseRedirect(redirect)


@login_required
def create_file(request, path):
    redirect = get_link_create(path)
    user_id = str(request.user.id)
    name = request.POST['new_name']
    create_user_file(user_id, path, name)
    return HttpResponseRedirect(redirect)


@login_required
def create_folder(request, path):
    redirect = get_link_create(path)
    user_id = str(request.user.id)
    name = request.POST['new_name']
    create_user_folder(user_id, path, name)
    return HttpResponseRedirect(redirect)


@login_required
def delete_file(request, path):
    redirect = get_link_delete(path)
    user_id = str(request.user.id)
    delete_user_file(user_id, '/' + path[:-1])
    return HttpResponseRedirect(redirect)


@login_required
def delete_folder(request, path):
    redirect = get_link_delete(path)
    user_id = str(request.user.id)
    delete_user_folder(user_id, '/' + path)
    return HttpResponseRedirect(redirect)


def change_name(request, path):
    redirect = get_link_create(path)
    if path == '':
        path = path + '/'
    user_id = str(request.user.id)
    old_name = request.POST['old_name']
    new_name = request.POST['new_name']
    rename(user_id + '/' + path, old_name, new_name)
    return HttpResponseRedirect(redirect)


def download_file(request, path):
    user_id = str(request.user.id)
    folder = 'media/' + user_id + '/' + path[:-1]
    f = open(folder, 'rb')
    myfile = f.readlines()
    f.close()
    response = HttpResponse(myfile)
    response['Content-Disposition'] = 'attachment; filename={}'.format(path[:-1].replace('/', '_'))
    return response


def download_folder(request, path):
    user_id = str(request.user.id)
    myfile, name = folder_archive(user_id, path)
    response = HttpResponse(myfile, content_type='.zip application/zip, application/octet-stream')
    response['Content-Disposition'] = 'attachment; filename={}'.format(name)
    return response


# Контроллер регистрирующий пользователя
class RegisterUserView(CreateView):
    model = DiskUser
    template_name = 'disk/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('disk:register_done')


# Контроллер, выводящий сообщение об успшной регистрации
class RegisterDoneView(TemplateView):
    template_name = 'disk/register_done.html'


# Страница входа
# В файле проекта установлен редирект на приложение disk
# LOGIN_REDIRECT_URL = '/disk/'
class DiskLoginView(LoginView):
    template_name = 'disk/login.html'


# Страница выхода
# Нужно, чтобы она была доступна только зарегистрированным пользователям
# Для этого добавляем класс LoginRequiredMixin
class DiskLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'disk/logout.html'


class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = DiskUser
    template_name = 'disk/delete_user.html'
    success_url = reverse_lazy('disk:index')

    # Сохраняем ключ пользователя
    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    # Выполнить выход перед удалением
    def post(self, request, *args, **kwargs):
        user_id = str(request.user.id)
        delete_user_folder(user_id, '')
        logout(request)
        return super().post(request, *args, **kwargs)

    # Извлечение удаляемой записи выполняется в get_object(),
    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class DiskPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    template_name = 'disk/password_change.html'
    success_url = reverse_lazy('disk:index')


# LoginRequiredMixin запрещает доступ к контроллеру готсям
class ChangeUserInfoView(LoginRequiredMixin, UpdateView):
    model = DiskUser
    form_class = ChangeUserInfoForm
    template_name = 'disk/change_user_info.html'
    success_url = reverse_lazy('disk:index')

    # В процессе работы контроллер должен извлечь запись из модели AdvUser,
    # представляющую текущего пользователя,
    # для чего нужно получить ключ текущего пользователя (user.pk)
    #
    # Метод dispatch исполняется в САМОМ НАЧАЛЕ работы контроллера-класса,
    # поэтому это лучшее место для получения ключа
    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    # Извлечение исправляемой записи выполняется в get_object(),
    # которую конроллер-класс унаслеовал от SingleObjectMixin
    # queryset может быть как передан, так и не передан
    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)

Halo/disk/templates/layout/basic.html
<!DOCTYPE html>
<html>
<head>
    {% load bootstrap4 %}
    {% load static %}

    <meta http-equiv="Content-Type" content="text/html"
            charset="UTF-8">
    <!-- Чтобы bootstrap правильно обработал страницу -->
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, shrink-to-fit=no">
    <title>{% block title %}Диск{% endblock %}</title>
    {% bootstrap_css %}
    <!-- Наши стили static/disk/style.css -->
    <link rel="stylesheet" type="text/css" href="{% static 'disk/style.css' %}">
    {% bootstrap_javascript jquery='slim' %}
</head>
<!-- container-fluid говррит о том, что верстка будет использовать bootstrap -->
<body class="container-fluid" oncontextmenu="return false;">
    <!-- Табличная верстка -->
        <!-- Горизонтальная навигация -->
        <header class="container-fluid own-dark">
            <div class="col-md-3 row justify-content-end" style="display:inline-block;">
                <div class="input-group input-group-sm mb-1">
                      <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroup-sizing-sm">🔍</span>
                      </div>
                      <input type="text" class="form-control" aria-label="Small" aria-describedby="inputGroup-sizing-sm">
                </div>
            </div>
            <div class="col-md-8" style="display:inline-block;"></div>
            <ul class="col-md-1 nav justify-content-end" style="display:inline-block;">
            <!-- Раскрывающиеся меню (если выполнен вход) -->
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle"
                   data-toggle="dropdown"
                   href="#"
                   role="button"
                   aria-haspopup="true"
                   aria-expanded="false"
                >Профиль</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'disk:index' %}">Главная</a>
                    <a class="dropdown-item" href="{% url 'music:index' %}">Музыка</a>
                    <a class="dropdown-item" href="{% url 'disk:profile_change' %}">Изменить личные данные</a>
                    <a class="dropdown-item" href="{% url 'disk:password_change' %}">Изменить пароль</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'disk:logout' %}">Выйти</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'disk:profile_delete' %}">Удалить аккаунт</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'disk:register' %}">Регистрация</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'disk:login'%}">Вход</a>
            </li>
            {% endif %}
        </ul>
    </header>
    <!-- Табличная верстка-->
    <div class="row own-white">
        <!-- col-md-auto -->
        <nav class="col-md-2 nav flex-column border own-gray">
             <button onClick="upload_form('{{ path }}');"
                    class="btn btn-warning own-button"
                    style="margin-top: 10%"
                    data-toggle="modal"
                    data-target="#exampleModal"
                    data-whatever="@mdo">(+) Загрузить</button>
            <div class="own-separator"></div>
            <button onClick="create_file('{{ path }}');"
                    class="btn btn-primary own-button"
                    data-toggle="modal"
                    data-target="#exampleModal"
                    data-whatever="@mdo">Создать файл</button>
            <button onClick="create_folder('{{ path }}');"
                    class="btn btn-primary own-button"
                    data-toggle="modal"
                    data-target="#exampleModal"
                    data-whatever="@mdo">Создать папку</button>
            <!-- Ссылка на приожение disk:other, передаем в приложение параметр page='about' -->
            <a class="nav-link root" href="{% url 'disk:about' %}">О приложении</a>
        </nav>
        <!-- py2 нужен, чтобы текст не примыкал к рамкам вплотную -->
        <section class="col border py-2">
            {% bootstrap_messages %}
            {% block content %}
            {% endblock %}
        </section>
    </div>
    <footer class="mt-3">
        <p class="text-right font-italic">The Halo</p>
    </footer>

    <script src="{% static 'js/menu.js' %}"></script>
    <script src="{% static 'js/path_bar.js' %}"></script>
    <script src="{% static 'js/create_objects.js' %}"></script>
</body>
</html>