Halo/Halo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('disk/', include('disk.urls')),
    path('music/', include('music.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Halo/disk/urls.py
from django.urls import path, re_path

from .views import index
from .views import about
from .views import other_page
from .views import change_name, \
                   upload_files, \
                   create_file,\
                   delete_file,\
                   delete_folder,\
                   create_folder,\
                   download_file, \
                   download_folder

from .views import RegisterUserView, RegisterDoneView
from .views import DiskLoginView, DiskLogoutView
from .views import DeleteUserView
from .views import DiskPasswordChangeView
from .views import ChangeUserInfoView

# Добавляем пространство имен
# Это поможет при рендеринге, можно указывать
# <namespace>:<app_name> <=> disk:upload
app_name = 'disk'

urlpatterns = [
    #    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),

    path('accounts/password/change/', DiskPasswordChangeView.as_view(), name='password_change'),

    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),

    # Путь к странцие входа
    path('accounts/login/', DiskLoginView.as_view(), name='login'),
    path('accounts/logout/', DiskLogoutView.as_view(), name='logout'),

    # sha_256(function_name) -> token
    # example: sha_256('about') -> a4262e1c9bcbc1721eb3fe13558154460a2b2a2d307daa32532478526ce6ccb1
    re_path(r'^63b8d67eb1ca393b5e69b31a5d126d553a3fb94afd7a60c90049e66c66c6b891/(?P<path>.*)', change_name, name='change_name'),
    re_path(r'^463d52e2aaa10e704eb0b24dea0eea8e9b86e38d52c28993eeebcf6ec01ec347/(?P<path>.*)', create_file, name='create_file'),
    re_path(r'^87b5c6b2b1e3e19601b421b8b81e199e4d27876d045610b5dcf078017caee694/(?P<path>.*)', delete_file, name='delete_file'),
    re_path(r'^5b53fba3b9601c8aa7ff13ce2d164f427a54f49b8873fa382e310f2162e0db08/(?P<path>.*)', create_folder, name='create_folder'),
    re_path(r'^e2a7114fca4f6f72dbfedc267c06cd4ff38644dbf11bae90efdf4d19c7ee7474/(?P<path>.*)', delete_folder, name='delete_folder'),
    re_path(r'^a3b2ceb1f2d110bf6c5f9f261a6f448a5be06e2e1a515e3e65bf7943300f89a3/(?P<path>.*)', upload_files, name='upload_files'),

    re_path(r'^b8c75dbaff47e7a2a24fb979a5c9f4bb91a22f8a83456c6006a6d21613c33f64/(?P<path>.*)', download_folder, name='download_folder'),
    re_path(r'^7898193c2ce6c4b3117e9ed4a3f09e615dd0cd89c3370770983e678b0c00e558/(?P<path>.*)', download_file, name='download_file'),
    path('a4262e1c9bcbc1721eb3fe13558154460a2b2a2d307daa32532478526ce6ccb1/', about, name='about'),
    re_path(r'^(?P<folder>.*)', other_page, name='other'),
    path('', index, name='index'),
]

Halo/music/urls.py
from django.urls import path

from .views import index, media_create
app_name = 'music'

urlpatterns = [
    path('add/', media_create, name='media_create'),
    path('', index, name='index'),
]

Halo/music/models.py
from django.db import models
from django.forms.models import modelform_factory


# Получаем путь для загрузки файла
# Если при загрузке файла не были
# введены данные Исполнителя и Альбома,
# то они устанавливаются в значение other
def get_upload_to(instance, filename):
    if instance.artist == '':
        artist = 'other'
    else:
        artist = instance.artist

    if instance.album == '':
        album = 'other'
    else:
        album = instance.album

    return 'music/songs/%s/%s/%s' % (artist, album, filename)


class MediaModel(models.Model):
    artist = models.CharField(blank=True, default=None, max_length=40, verbose_name='Исполнитель')
    album = models.CharField(blank=True, default=None, max_length=40, verbose_name='Альбом')
    song = models.CharField(blank=True, default=None, max_length=100, verbose_name='Композиция')
    media_file = models.FileField(upload_to=get_upload_to)


MediaForm = modelform_factory(MediaModel, fields={'artist', 'album', 'song', 'media_file'})

Halo/music/views.py
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect

from .models import MediaForm
from .utilities import get_context
from .utilities import change_music_meta


# Основаная страница
def index(request):
    template = loader.get_template('music/index.html')
    artist, title, album, time, song_url = get_context()
    form = MediaForm()
    context = {'artist': artist,
               'title': title,
               'album': album,
               'time': time,
               'song_url': song_url,
               'form': form
               }
    return HttpResponse(template.render(context, request))


# Загрузка файла на сервер
def media_create(request):
    template = loader.get_template('music/create.html')
    if request.method == "POST":
        form = MediaForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # Редактируем информацию трека по данным формы
            change_music_meta(request.POST['artist'],
                              request.POST['song'],
                              request.POST['album'],
                              request.FILES['media_file'].name
                              )
            return HttpResponseRedirect('http://localhost:8000/music/')
    else:
        form = MediaForm()
    return HttpResponse(template.render({'form': form}, request))

Halo/music/templates/music/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Music</title>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    {% bootstrap_javascript jquery='slim' %}
</head>
<body class="container-fluid own-dark">
    <div class="row">
        <button type="button" class="btn btn-primary m-auto text-center" data-toggle="modal" data-target="#exampleModalCenter">
            Добавить композицию в библиотеку
        </button>
    </div>
    <div class="row">
        <a class="btn btn-success m-auto text-center" href="{% url 'music:index' %}">
            Вернуться к прослушиванию
        </a>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Добавить песню</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
              <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form layout='horizontal' %}
                {% buttons submit='Добавить' %}{% endbuttons %}
              </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
          </div>
        </div>
      </div>
    </div>
</body>
</html>

Halo/music/templates/music/index.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html"
            charset="UTF-8">
    <!-- Чтобы bootstrap правильно обработал страницу -->
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, shrink-to-fit=no">
    <title>{% block title %}Music{% endblock %}</title>
    {% bootstrap_css %}
    <!-- Наши стили static/main/style.css -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    {% bootstrap_javascript jquery='slim' %}
</head>
<body class="container-fluid own-dark">

    <header class="container-fluid own-dark">
            <ul class="nav navbar-dark justify-content-end">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle"
                   data-toggle="dropdown"
                   href="#"
                   role="button"
                   aria-haspopup="true"
                   aria-expanded="false"
                >Профиль</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'music:index' %}">Обновить</a>
                    <a class="dropdown-item" href="{% url 'disk:index' %}">Диск</a>
                    <button type="button" class="dropdown-item" data-toggle="modal" data-target="#exampleModalCenter">
                        Добавить композицию в библиотеку
                    </button>
                    <a class="dropdown-item" href="{% url 'disk:profile_change' %}">Изменить личные данные</a>
                    <a class="dropdown-item" href="{% url 'disk:password_change' %}">Изменить пароль</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'disk:logout' %}">Выйти</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'disk:profile_delete' %}">Удалить аккаунт</a>
                </div>
            </li>
        </ul>
    </header>

    <div class="mb-4 text-center">
        <h1 class="display-1 ">MUSIC</h1>
    </div>
    <div class="row hidden">
        <div class="col-md-4 mx-auto flex-column">
            <input class="own-input" type="text">
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 mx-auto flex-column own-canvas own-gradient">
            <div class="row text-center">
                <div class="col-md-6 mx-auto mt-3 mb-1">
                    <img src="../media/music/albums/img.jpg" class="col mx-auto">
                </div>
                <div class="col-md-6 m-auto own-yellow-font">
                    <div>&times;&times;&times;</div>
                    <div class="text-break">{{ title }}</div>
                    <div class="text-break">{{ artist }}</div>
                    <div>{{ time }}</div>
                    <div>{{ album }}</div>
                </div>
            </div>
            <div class="col mx-auto">
                <audio src="{{ song_url }}" controls="">
                </audio>
            </div>
        </div>
    </div>

    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Добавить песню</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
              <form method="post" enctype="multipart/form-data" action="{% url 'music:media_create'%}">
                {% csrf_token %}
                {% bootstrap_form form layout='horizontal' %}
                {% buttons submit='Добавить' %}{% endbuttons %}
              </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
          </div>
        </div>
      </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" integrity="sha256-qM7QTJSlvtPSxVRjVWNM2OfTAz/3k5ovHOKmKXuYMO4=" crossorigin="anonymous"></script>

</body>
</html>